port: 7892 # HTTP ä»£ç†ç«¯å£
socks-port: 7893 # SOCKS5 ä»£ç†ç«¯å£
mixed-port: 7890 # HTTP/SOCKS æ··åˆä»£ç†ç«¯å£
allow-lan: true # å…è®¸å±€åŸŸç½‘è®¾å¤‡è¿æ¥ä»£ç†
bind-address: "*" # ç»‘å®šåœ°å€ï¼Œé»˜è®¤ä¸ºæ‰€æœ‰ IP åœ°å€
#authentication:
#  - "username:password" # HTTP/SOCKS ä»£ç†è®¤è¯ï¼Œæ ¼å¼ä¸º ç”¨æˆ·å:å¯†ç 
#skip-auth-prefixes:
#  - 127.0.0.1/8 # è·³è¿‡æœ¬åœ°åœ°å€çš„è®¤è¯
#  - ::1/128 # è·³è¿‡ IPv6 æœ¬åœ°åœ°å€çš„è®¤è¯
#lan-allowed-ips:
#  - 0.0.0.0/0 # å…è®¸å±€åŸŸç½‘è®¿é—®çš„ IP åœ°å€èŒƒå›´ (IPv4)
#  - ::/0 # å…è®¸å±€åŸŸç½‘è®¿é—®çš„ IP åœ°å€èŒƒå›´ (IPv6)
#lan-disallowed-ips:
#  - 192.168.0.3/32 # å±€åŸŸç½‘ç¦æ­¢è®¿é—®çš„ç‰¹å®š IP åœ°å€

# always å¼€å¯ï¼Œå¼ºåˆ¶åŒ¹é…æ‰€æœ‰è¿›ç¨‹
# strict é»˜è®¤ï¼Œç”± Clash åˆ¤æ–­æ˜¯å¦å¼€å¯
# off ä¸åŒ¹é…è¿›ç¨‹ï¼Œæ¨èåœ¨è·¯ç”±å™¨ä¸Šä½¿ç”¨æ­¤æ¨¡å¼
find-process-mode: off
mode: rule # å·¥ä½œæ¨¡å¼ä¸ºè§„åˆ™æ¨¡å¼
geodata-mode: false # æ›´æ”¹ geoip ä½¿ç”¨æ–‡ä»¶ï¼Œmmdb æˆ–è€… datï¼Œå¯é€‰ true/false,trueä¸º dat
# standardï¼šæ ‡å‡†åŠ è½½å™¨
# memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)
geodata-loader: memconservative
geox-url: # Geo æ•°æ®åº“é…ç½®ï¼Œç”¨äºåœ°ç†ä½ç½®å’Œ ASN åŒ¹é…
  geoip: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@release/geoip.dat" # GeoIP æ•°æ®åº“
  geosite: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@release/geosite.dat" # GeoSite æ•°æ®åº“
  mmdb: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb" # GeoIP mmdb æ•°æ®åº“
  asn: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb" # ASN æ•°æ®åº“
geo-auto-update: false # å¼€å¯è‡ªåŠ¨æ›´æ–° Geo æ•°æ®åº“
geo-update-interval: 24 # Geo æ•°æ®åº“æ›´æ–°é—´éš” (å•ä½: å°æ—¶)
# GeoSite ä½¿ç”¨çš„åŒ¹é…å™¨å®ç°ï¼Œå¯ç”¨çš„å®ç°ï¼š
# - succinctï¼ˆé»˜è®¤ï¼Œä¸è§„åˆ™é›†ç›¸åŒï¼‰
# - mphï¼ˆæ¥è‡ª V2Rayï¼Œåœ¨ Xray ä¸­ä¹Ÿæ˜¯ `hybrid`ï¼‰
geosite-matcher: succinct

global-ua: clash.meta # è‡ªå®šå…¨å±€ UA
etag-support: true # å¤–éƒ¨èµ„æºä¸‹è½½çš„ ETag æ”¯æŒ
# silent é™é»˜ï¼Œä¸è¾“å‡º
# error ä»…è¾“å‡ºå‘ç”Ÿé”™è¯¯è‡³æ— æ³•ä½¿ç”¨çš„æ—¥å¿—
# warning è¾“å‡ºå‘ç”Ÿé”™è¯¯ä½†ä¸å½±å“è¿è¡Œçš„æ—¥å¿—ï¼Œä»¥åŠ error çº§åˆ«å†…å®¹
# info è¾“å‡ºä¸€èˆ¬è¿è¡Œçš„å†…å®¹ï¼Œä»¥åŠ error å’Œ warning çº§åˆ«çš„æ—¥å¿—
# debug å°½å¯èƒ½çš„è¾“å‡ºè¿è¡Œä¸­æ‰€æœ‰çš„ä¿¡æ¯
log-level: info # æ—¥å¿—ç­‰çº§
ipv6: true # å¯ç”¨ IPv6
#tls: # TLS ç›¸å…³é…ç½®
#  certificate: string # TLS è¯ä¹¦
#  private-key: string # TLS ç§é’¥
#  custom-certifactes: # è‡ªå®šä¹‰è¯ä¹¦
#    - |
#      -----BEGIN CERTIFICATE-----
#      format/pem...
#      -----END CERTIFICATE-----

external-controller: 0.0.0.0:9090 # å¤–éƒ¨æ§åˆ¶ç«¯å£
#external-controller-tls: 0.0.0.0:9443 # TLS å¤–éƒ¨æ§åˆ¶ç«¯å£
secret: "" # æ§åˆ¶æ¥å£å¯†é’¥

# RESTful API CORSæ ‡å¤´é…ç½®
external-controller-cors: # CORS é…ç½®
  allow-origins: #å…è®¸æ¥æº
    - '*'
  allow-private-network: true # å…è®¸ç§æœ‰ç½‘ç»œè®¿é—®
#external-controller-unix: mihomo.sock  # Unix Socket æ§åˆ¶æ¥å£
#external-controller-pipe: \\.\pipe\mihomo  # Windows ç®¡é“æ¥å£

unified-delay: true # å¼€å¯ç»Ÿä¸€å»¶è¿Ÿæ—¶
tcp-concurrent: true # å¯ç”¨ TCP å¹¶å‘è¿æ¥
external-ui: ui # å¤–éƒ¨ UI ç›®å½•
external-ui-name: xd # å¤–éƒ¨ UI åç§°
external-ui-url: "https://ghfast.top/github.com/Zephyruso/zashboard/releases/latest/download/dist.zip" # å¤–éƒ¨ UI ä¸‹è½½é“¾æ¥
external-doh-server: /dns-query # å¤–éƒ¨ DoH æœåŠ¡å™¨
#interface-name:  # ä½¿ç”¨çš„ç½‘ç»œæ¥å£åç§°
#routing-mark:  # è·¯ç”±æ ‡è®°

# ç¼“è§£ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜
# https://github.com/vernesong/OpenClash/issues/2614
disable-keep-alive: true # ç¦ç”¨ TCP Keep Aliveï¼Œåœ¨ Android é»˜è®¤ä¸º true
keep-alive-idle: 15 # Keep-Alive ç©ºé—²æ—¶é—´ (å•ä½: ç§’)
keep-alive-interval: 15 # Keep-Alive é—´éš”æ—¶é—´ (å•ä½: ç§’)

# å®éªŒæ€§åŠŸèƒ½é…ç½®
experimental:
  quic-go-disable-gso: false # ç¦ç”¨ QUIC åè®®ä¸­çš„ GSO (Generic Segmentation Offload) åŠŸèƒ½
  quic-go-disable-ecn: false #ç¦ç”¨ECN
  dialer-ip4p-convert: false # å¯ç”¨IP4Påœ°å€è½¬æ¢

# æœ¬åœ° DNS è§£æé…ç½®
hosts:
  dns.alidns.com:
    - 223.5.5.5
    - 223.6.6.6
    - 2400:3200::1
    - 2400:3200:baba::1
  dns.google:
    - 8.8.4.4
    - 8.8.8.8
    - 2001:4860:4860::8844
    - 2001:4860:4860::8888

# ç¼“å­˜
profile:
  store-selected: true # å­˜å‚¨å·²é€‰æ‹©çš„ä»£ç†ç»„
  store-fake-ip: true # å­˜å‚¨ Fake IP åœ°å€

# ç½‘ç»œæ—¶é—´åè®® (NTP) è®¾ç½®
ntp:
  enable: false # å¯ç”¨ NTP åŠŸèƒ½
  write-to-system: false # å°†åŒæ­¥çš„æ—¶é—´å†™å…¥ç³»ç»Ÿæ—¶é’Ÿï¼Œéœ€rootæƒé™
  server: ntp.ntsc.ac.cn # NTP æœåŠ¡å™¨åœ°å€
  port: 123 # NTP æœåŠ¡å™¨ç«¯å£ï¼Œé»˜è®¤ä½¿ç”¨ 123 ç«¯å£
  interval: 30 # åŒæ­¥æ—¶é—´çš„é—´éš” (å•ä½: åˆ†é’Ÿ)

# sniffer é…ç½®ï¼šç”¨äºæ£€æµ‹å’Œå¤„ç†ä¸åŒåè®®çš„æµé‡
sniffer:
  enable: true # æ˜¯å¦å¯ç”¨ sniffer ä¾¦æµ‹åŠŸèƒ½ï¼Œé»˜è®¤å…³é—­
  force-dns-mapping: false # å¯¹ redir-host ç±»å‹è¯†åˆ«çš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  parse-pure-ip: false # å¯¹æ‰€æœ‰æœªè·å–åˆ°åŸŸåçš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  override-destination: false # æ˜¯å¦ä½¿ç”¨å—…æ¢ç»“æœä½œä¸ºå®é™…è®¿é—®ï¼Œé»˜è®¤ä¸º true
  sniff:
    HTTP:
      ports: [80, 8080-8880] # å¯¹ HTTP æµé‡è¿›è¡Œå—…æ¢çš„ç«¯å£èŒƒå›´ï¼Œå¸¸ç”¨äºç½‘ç«™å’Œåº”ç”¨
      override-destination: true # è¦†ç›–ç›®æ ‡åœ°å€ä»¥å¼ºåˆ¶æµé‡èµ°ä»£ç†æˆ–è§„åˆ™åŒ¹é…
    TLS:
      ports: [443, 8443] # å¯¹ HTTPS æµé‡çš„ç«¯å£è¿›è¡Œå—…æ¢ï¼Œé€šå¸¸ç”¨äºåŠ å¯†è¿æ¥
    QUIC:
      ports: [443, 8443] # å¯¹ QUIC åè®®çš„æµé‡è¿›è¡Œå—…æ¢ï¼ŒQUI C å¸¸ç”¨äºæ”¹è¿› HTTPS è¿æ¥çš„é€Ÿåº¦
  force-domain:
    - +.v2ex.com # å¯¹æŒ‡å®šåŸŸåå¼ºåˆ¶è§£æï¼Œå³ä½¿ IP åœ°å€å·²ç¼“å­˜æˆ–å·²çŸ¥
  skip-domain:
    - Mijia.Cloud.com # è·³è¿‡æŒ‡å®šåŸŸåï¼Œä¸å¯¹å…¶è¿›è¡Œå—…æ¢å¤„ç†ï¼ˆå¦‚æ™ºèƒ½å®¶å±…æµé‡ï¼‰
  skip-src-address:
    - 192.168.0.3/32 # è·³è¿‡æ¥æº IP åœ°å€ï¼Œä¸å¯¹å…¶è¿›è¡Œå—…æ¢
  skip-dst-address:
    - 192.168.0.3/32 # è·³è¿‡ç›®æ ‡ IP åœ°å€ï¼Œä¸å¯¹å…¶è¿›è¡Œå—…æ¢

# tun é…ç½®ï¼šç”¨äºå¯ç”¨ TUN æ¨¡å¼ï¼Œä¼˜åŒ–æµé‡è·¯ç”±å’Œ IP è®¾ç½®
tun:
  enable: true # å¯ç”¨ TUN æ¨¡å¼ï¼Œç”¨äºé€æ˜ä»£ç†
  stack: gvisor # ä½¿ç”¨ç©ºé—´ç½‘ç»œæ ˆå¤„ç†æµé‡ï¼Œå¯ç”¨å€¼ï¼š system/gvisor/mixed
  auto-route: true # è‡ªåŠ¨è®¾ç½®å…¨å±€è·¯ç”±ï¼Œå¯ä»¥è‡ªåŠ¨å°†å…¨å±€æµé‡è·¯ç”±è¿›å…¥ tun ç½‘å¡ã€‚
  # auto-redirect: true # è‡ªåŠ¨é…ç½® iptables/nftables ä»¥é‡å®šå‘ TCP è¿æ¥, éœ€è¦auto-routeå·²å¯ç”¨, éœ€è¦rootæƒé™
  auto-detect-interface: true # è‡ªåŠ¨é€‰æ‹©æµé‡å‡ºå£æ¥å£ï¼Œå¤šå‡ºå£ç½‘å¡åŒæ—¶è¿æ¥çš„è®¾å¤‡å»ºè®®æ‰‹åŠ¨æŒ‡å®šå‡ºå£ç½‘å¡
  dns-hijack:
    - any:53 # åŠ«æŒæ‰€æœ‰ 53 ç«¯å£çš„ DNS è¯·æ±‚
    - tcp://any:53
  device: mihomo # æŒ‡å®š TUN è®¾å¤‡åç§°ï¼Œé»˜è®¤ä¸º utun
  mtu: 1500 # è®¾ç½®æœ€å¤§ä¼ è¾“å•å…ƒ (MTU)ï¼Œæé«˜ç½‘ç»œååé‡
  strict-route: true # å¯ç”¨ auto-route æ—¶æ‰§è¡Œä¸¥æ ¼çš„è·¯ç”±è§„åˆ™
  gso: true # é€šç”¨åˆ†æ®µå¸è½½ (GSO)ï¼Œæé«˜ç½‘ç»œæ€§èƒ½
  gso-max-size: 65536 # è®¾ç½® GSO æœ€å¤§åˆ†æ®µå¤§å°ä¸º 65536 å­—èŠ‚
  udp-timeout: 300 # è®¾ç½® UDP è¶…æ—¶æ—¶é—´ä¸º 300 ç§’ï¼Œä¼˜åŒ– NAT æ˜ å°„
  # iproute2-table-index: 2022 # ä½¿ç”¨æŒ‡å®šçš„è·¯ç”±è¡¨ç´¢å¼• (iproute2)
  # iproute2-rule-index: 9000 # è®¾ç½®è·¯ç”±è§„åˆ™çš„ç´¢å¼• (iproute2)
  endpoint-independent-nat: false # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NATï¼Œæ€§èƒ½å¯èƒ½ä¼šç•¥æœ‰ä¸‹é™ï¼Œæ‰€ä»¥ä¸å»ºè®®åœ¨ä¸éœ€è¦çš„æ—¶å€™å¼€å¯

# DNS é…ç½®ï¼šæ§åˆ¶ DNS æŸ¥è¯¢è¡Œä¸ºï¼Œæ”¯æŒå¢å¼ºæ¨¡å¼å’Œå‡ IP åŠŸèƒ½
# æŸ¥è¯¢ DNS æ˜¯å¦æ”¯æŒ H3 æŒ‡ä»¤:
#  curl https://1.1.1.1/dns-query --http3-only -vI
#  q www.baidu.com @https://1.1.1.1/dns-query --http3
dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:7874
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  fake-ip-filter:
  - RULE-SET:private_domain,fakeip_filter_domain,cn_domain,dns_domain
  - "+.github.com"
  - "+.githubusercontent.com"
  - "+.raw.githubusercontent.com"
  - "+.gitlab.com"
  - "+.docker.io"
  - "+.npmjs.org"
  - "+.pypi.org"

  nameserver-policy:
    "RULE-SET:private_domain,cn_domain":
      - 220.189.127.106
      - 220.189.127.107
      - tcp://220.189.127.106:53
      - tcp://220.189.127.107:53
    "RULE-SET:geolocation-!cn":
      - tls://1.1.1.1:853
      - tls://8.8.8.8:853

  nameserver:
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853

  proxy-server-nameserver:
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853

  direct-nameserver:
    - 220.189.127.106
    - 220.189.127.107

  direct-nameserver-follow-policy: true

ipcidr_mrs: &ipcidr_mrs { type: http, interval: 28800, behavior: ipcidr, format: mrs, proxy: ğŸ¯ å…¨çƒç›´è¿ }
domain_mrs: &domain_mrs { type: http, interval: 28800, behavior: domain, format: mrs, proxy: ğŸ¯ å…¨çƒç›´è¿ }
  
rule-providers:
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    proxy: DIRECT
    url: "https://jsd.onmicrosoft.cn/gh/Kwisma/clash-rules@release/direct.mrs"
    path: ./ruleset/China_Domain.mrs
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    proxy: DIRECT
    url: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs"
    path: ./ruleset/Private_Domain.mrs
  fakeip_filter_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    proxy: DIRECT
    url: "https://jsd.onmicrosoft.cn/gh/DustinWin/ruleset_geodata@mihomo-ruleset/fakeip-filter.mrs"
    path: ./ruleset/Fakeip_Filter_Domain.mrs
  dns_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    proxy: DIRECT
    url: "https://jsd.onmicrosoft.cn/gh/peiyingyao/Rule-for-OCD@master/rule/Clash/DNS/DNS_OCD_Domain.mrs"
    path: ./ruleset/DNS_Domain.mrs
  Steam_CDN_Classical:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml
    interval: 28800
  Custom_Port_Direct:
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml
    interval: 28800
  cn_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/Kwisma/clash-rules@release/direct.mrs"
    path: ./ruleset/CN_Domain.mrs
  cn_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/Kwisma/clash-rules@release/cncidr.mrs"
    path: ./ruleset/CN_IP.mrs
  private_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs"
    path: ./ruleset/Private_Domain.mrs
  private_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs"
    path: ./ruleset/Private_IP.mrs
  iptest:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/xiaodaiceshi/cf-worker-mihomo/main/rules/iptest.yaml"
    path: ./ruleset/iptest.yaml
    interval: 28800
  cloudflare:
    type: http
    behavior: classical
    format: yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.yaml"
    path: ./ruleset/cloudflare.yaml
    interval: 28800
  PayPal:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
    path: ./ruleset/PayPal.yaml
    interval: 28800
  custom_proxy:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/xiaodaiceshi/cf-worker-mihomo/main/rules/custom_proxy.yaml"
    path: ./ruleset/custom_proxy.yaml
    interval: 28800
  custom_direct:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/xiaodaiceshi/cf-worker-mihomo/main/rules/custom_direct.yaml"
    path: ./ruleset/custom_direct.yaml
    interval: 28800
  embydirect_domain:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/xiaodaiceshi/cf-worker-mihomo/main/rules/embydirect.yaml"
    path: ./ruleset/embydirect_domain.yaml
    interval: 28800
  github_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs"
    path: ./ruleset/github_domain.mrs
  epic_domain:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml"
    path: ./ruleset/epic_domain.yaml
    interval: 28800
  microsoft_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs"
    path: ./ruleset/microsoft_domain.mrs
  ai_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/openai.mrs"
    path: ./ruleset/ai_domain.mrs
  onedrive_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/onedrive.mrs"
    path: ./ruleset/onedrive_domain.mrs
  apple_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs"
    path: ./ruleset/apple_domain.mrs
  emby_domain:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/xiaodaiceshi/cf-worker-mihomo/main/rules/embyproxy.yaml"
    path: ./ruleset/emby_domain.yaml
    interval: 28800
  twitter_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs"
    path: ./ruleset/twitter_domain.mrs
  youtube_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs"
    path: ./ruleset/youtube_domain.mrs
  google_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs"
    path: ./ruleset/google_domain.mrs
  telegram_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs"
    path: ./ruleset/telegram_domain.mrs
  netflix_domain:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs"
    path: ./ruleset/netflix_domain.mrs
  spotify_domain:
    <<: *domain_mrs
    url: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs"
    path: ./ruleset/spotify_domain.mrs
  google_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs"
    path: ./ruleset/google_ip.mrs
  netflix_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs"
    path: ./ruleset/netflix_ip.mrs
  twitter_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs"
    path: ./ruleset/twitter_ip.mrs
  telegram_ip:
    <<: *ipcidr_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs"
    path: ./ruleset/telegram_ip.mrs
  geolocation-!cn:
    <<: *domain_mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs"
    path: ./ruleset/geolocation-!cn.mrs
